# FILE: v2/podcast.py
# PURPOSE: Generate dual-length podcast MP3s from a V2 book.yaml using Microsoft edge-tts.
# OWNS: Podcast audio generation (short + long), voice selection, text-to-speech pipeline.
# EXPORTS: generate_podcast, main.
# DOCS: README.md, v2/schema.py

"""
Rixie V2 — Podcast Generator

Standalone CLI that reads a workspace/book.yaml and produces two MP3 files:

  SHORT (quick listen):
    Title → Abstract → short_summary₁ → short_summary₂ → ...

  LONG (deep dive):
    Title → Abstract → detailed_summary₁ → detailed_summary₂ → ...

Uses Microsoft's neural edge-tts engine (400+ voices, free, high quality).
Output: {slug}-podcast-short.mp3 and {slug}-podcast-long.mp3
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# ── Constants ──
DEFAULT_VOICE = "en-US-AriaNeural"
DEFAULT_RATE = "+5%"
SUPPORTED_EXTENSIONS = {".epub", ".md", ".txt", ".pdf"}


def _find_edge_tts() -> str | None:
    """Find the edge-tts binary path."""
    path = shutil.which("edge-tts")
    if path:
        return path
    # Try uv tool bin
    uv_bin = Path.home() / ".local" / "bin" / "edge-tts"
    if uv_bin.exists():
        return str(uv_bin)
    # Windows: check common uv tool locations
    for candidate in [
        Path.home() / "AppData" / "Roaming" / "uv" / "tools" / "edge-tts",
        Path.home() / ".cargo" / "bin" / "edge-tts",
    ]:
        if (candidate / "Scripts" / "edge-tts.exe").exists():
            return str(candidate / "Scripts" / "edge-tts.exe")
        if candidate.with_suffix(".exe").exists():
            return str(candidate.with_suffix(".exe"))
    return None


def _clean_for_tts(text: str) -> str:
    """Clean markdown/HTML artifacts for natural TTS reading."""
    # Remove markdown links: [text](url) → text
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # Remove markdown bold/italic markers
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"__([^_]+)__", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    text = re.sub(r"_([^_]+)_", r"\1", text)
    # Remove code blocks
    text = re.sub(r"```[\s\S]*?```", " [code omitted] ", text)
    # Remove inline code
    text = re.sub(r"`([^`]+)`", r"\1", text)
    # Replace HTML entities
    text = text.replace("&amp;", "and")
    text = text.replace("&mdash;", "—")
    text = text.replace("&ndash;", "–")
    text = text.replace("&bull;", "•")
    text = text.replace("&hellip;", "…")
    # Remove other HTML tags
    text = re.sub(r"<[^>]+>", " ", text)
    # Collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _build_script(
    book_name: str,
    authors: list[str],
    abstract: str,
    chapters: list[dict[str, Any]],
    mode: str,  # "short" or "long"
) -> str:
    """Build the full TTS script text from book data.

    Structure:
      - Title and author
      - Abstract (ultra-dense summary)
      - Chapter summaries (short or detailed based on mode)
    """
    parts: list[str] = []

    # ── Title ──
    parts.append(f"{book_name}.")
    if authors:
        parts.append(f"By {', '.join(authors)}.")
    parts.append("")  # pause

    # ── Abstract ──
    if abstract.strip():
        parts.append("Abstract.")
        parts.append(_clean_for_tts(abstract))
        parts.append("")

    # ── Chapters ──
    if not chapters:
        parts.append("No chapters available for this book.")
    else:
        for i, ch in enumerate(chapters, start=1):
            ch_title = ch.get("title") or f"Chapter {i}"

            if mode == "short":
                summary = ch.get("short_summary") or ""
                label = f"Chapter {i}. {ch_title}."
            else:
                summary = ch.get("detailed_summary") or ch.get("short_summary") or ""
                label = f"Chapter {i}. {ch_title}. Detailed summary."

            parts.append(label)
            if summary.strip():
                parts.append(_clean_for_tts(summary))
            else:
                parts.append("No summary available for this chapter.")
            parts.append("")  # pause between chapters

    # ── End ──
    parts.append(f"End of {book_name}.")
    parts.append("Generated by Rixie V2.")

    return "\n".join(parts)


def generate_podcast(
    workspace_dir: Path,
    *,
    voice: str = DEFAULT_VOICE,
    rate: str = DEFAULT_RATE,
    mode: str = "both",  # "short", "long", or "both"
    output_dir: Path | None = None,
) -> dict[str, Path]:
    """Generate podcast MP3(s) from a V2 workspace.

    Args:
        workspace_dir: Path to the V2 book workspace (contains book.yaml).
        voice: Microsoft neural voice name (default: en-US-AriaNeural).
        rate: Speech rate adjustment, e.g. "+5%", "-10%" (default: +5%).
        mode: "short", "long", or "both" (default: both).
        output_dir: Optional output directory (defaults to workspace_dir).

    Returns:
        Dict mapping mode name to output MP3 path.
    """
    edge_tts_bin = _find_edge_tts()
    if not edge_tts_bin:
        raise RuntimeError(
            "edge-tts not found. Install with: uv tool install edge-tts\n"
            "Then ensure edge-tts is on your PATH."
        )

    book_yaml = workspace_dir / "book.yaml"
    if not book_yaml.exists():
        raise FileNotFoundError(f"book.yaml not found in {workspace_dir}")

    data = yaml.safe_load(book_yaml.read_text(encoding="utf-8")) or {}
    meta = data.get("metadata", {})
    book_name = meta.get("title") or workspace_dir.name
    authors = meta.get("authors") or []
    slug = meta.get("slug") or workspace_dir.name
    overview = data.get("overview", {}) or {}
    abstract = overview.get("ultra_dense_summary") or ""
    chapters_raw = data.get("chapters") or []
    chapters = sorted(chapters_raw, key=lambda c: c.get("order", 0))

    print(f"   🎙 Generating podcast for: {book_name}")
    print(f"      Slug: {slug}")
    print(f"      Chapters: {len(chapters)}")
    print(f"      Voice: {voice}")
    print(f"      Rate: {rate}")
    print(f"      Mode: {mode}")

    if not chapters:
        print("   ⚠️  No chapters — skipping podcast generation")
        return {}

    out_dir = output_dir or workspace_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    result: dict[str, Path] = {}

    for current_mode in (["short", "long"] if mode == "both" else [mode]):
        script = _build_script(book_name, authors, abstract, chapters, current_mode)

        # Write script to temp file (edge-tts can read from file)
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".txt", delete=False, encoding="utf-8"
        ) as tf:
            tf.write(script)
            script_path = Path(tf.name)

        out_path = out_dir / f"{slug}-podcast-{current_mode}.mp3"

        try:
            print(f"   🔊 Synthesizing {current_mode} version...")
            print(f"      Script: {len(script):,} chars")

            # edge-tts --voice <voice> --rate <rate> -f <script.txt> --write-media <out.mp3>
            cmd = [
                edge_tts_bin,
                "--voice", voice,
                "--rate", rate,
                "-f", str(script_path),
                "--write-media", str(out_path),
            ]
            subprocess.run(cmd, check=True, capture_output=True, text=True, timeout=600)

            file_size = out_path.stat().st_size if out_path.exists() else 0
            print(f"   ✅ {current_mode.capitalize()}: {out_path.name} ({file_size:,} bytes)")

            result[current_mode] = out_path
        except subprocess.TimeoutExpired:
            print(f"   ❌ {current_mode.capitalize()} synthesis timed out after 10 minutes")
        except subprocess.CalledProcessError as e:
            print(f"   ❌ {current_mode.capitalize()} synthesis failed: {e.stderr}")
        finally:
            # Clean up temp script file
            try:
                script_path.unlink()
            except OSError:
                pass

    return result


def main(argv: list[str] | None = None) -> int:
    """CLI entry: python -m v2.podcast <workspace_dir> [options]"""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate dual-length podcast MP3s from a Rixie V2 book workspace.",
    )
    parser.add_argument(
        "workspace_dir",
        help="Path to the V2 book workspace directory (contains book.yaml).",
    )
    parser.add_argument(
        "--voice",
        default=DEFAULT_VOICE,
        help=f"Microsoft neural voice name (default: {DEFAULT_VOICE}). "
             "Use 'edge-tts --list-voices' to see all options.",
    )
    parser.add_argument(
        "--rate",
        default=DEFAULT_RATE,
        help=f"Speech rate adjustment, e.g. '+10%%', '-5%%' (default: {DEFAULT_RATE}).",
    )
    parser.add_argument(
        "--mode",
        choices=["short", "long", "both"],
        default="both",
        help="Which podcast version(s) to generate (default: both).",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory for MP3 files (default: workspace directory).",
    )
    parser.add_argument(
        "--list-voices",
        action="store_true",
        help="List available edge-tts voices and exit.",
    )

    if argv is not None:
        args = parser.parse_args(argv)
    else:
        args = parser.parse_args()

    # ── List voices mode ──
    if args.list_voices:
        edge_tts_bin = _find_edge_tts()
        if not edge_tts_bin:
            print("❌ edge-tts not found. Install with: uv tool install edge-tts")
            return 1
        subprocess.run([edge_tts_bin, "--list-voices"])
        return 0

    workspace_dir = Path(args.workspace_dir).resolve()
    if not workspace_dir.is_dir():
        print(f"❌ Not a directory: {workspace_dir}")
        return 1

    output_dir = Path(args.output_dir).resolve() if args.output_dir else None

    try:
        result = generate_podcast(
            workspace_dir,
            voice=args.voice,
            rate=args.rate,
            mode=args.mode,
            output_dir=output_dir,
        )
        if result:
            print(f"\n✅ Podcast generation complete:")
            for mode_name, path in result.items():
                print(f"   {mode_name}: {path}")
            return 0
        else:
            print("\n⚠️  No podcasts generated.")
            return 1
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
